### ISSUE TITLE
archlinux

### ISSUE THREAD

**Issue by philippehenin** [McArcady/lnp-forge#24]
Builded on newly create archlinix from git:

[philippehenin@redmibook-16 lnp-forge]$ ./bin/lnp-forge build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20200718.124841
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed components' tarballs
[INFO ]    Retrieving 'lnp-0.14a' from 'https://github.com/Pidgeot/python-lnp'
[INFO ]    Got 'lnp-0.14a'
[INFO ]    Retrieving 'df_47_04_linux' from http://www.bay12games.com/dwarves/
[INFO ]    Got 'df_47_04_linux'
[INFO ]    Retrieving 'graphics-47.04' from 'https://github.com/McArcady/DFgraphics.git'
[INFO ]    Got 'graphics-47.04'
[INFO ]    Retrieving 'advanced_profiles' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/embarks/
[INFO ]    Got 'advanced_profiles'
[INFO ]    Retrieving 'default_profiles' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/embarks/
[INFO ]    Got 'default_profiles'
[INFO ]    Retrieving 'starting_scenarios' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/embarks/
[INFO ]    Got 'starting_scenarios'
[INFO ]    Retrieving 'tutorial_profiles' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/embarks/
[INFO ]    Got 'tutorial_profiles'
[INFO ]    Retrieving 'Classic_LNP' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/keybinds/
[INFO ]    Got 'Classic_LNP'
[INFO ]    Retrieving 'New_LNP' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/keybinds/
[INFO ]    Got 'New_LNP'
[INFO ]    Retrieving 'PeridexisErrant' from https://raw.githubusercontent.com/Lazy-Newb-Pack/LNP-shared-core/master/keybinds/
[INFO ]    Got 'PeridexisErrant'
[INFO ]    Retrieving 'Keyboard_FR' from https://raw.githubusercontent.com/McArcady/LNP-shared-core/master/keybinds/
[INFO ]    Got 'Keyboard_FR'
[INFO ]    Retrieving 'dfhack-0.47.04-r1' from 'https://github.com/DFHack/dfhack.git'
[INFO ]    Got 'dfhack-0.47.04-r1'
[INFO ]    Retrieving 'twbt-04704' from 'https://github.com/thurin/df-twbt.git'
[INFO ]    Got 'twbt-04704'
[INFO ]    Retrieving 'therapist-v41.1.7' from 'https://github.com/Dwarf-Therapist/Dwarf-Therapist'
[INFO ]    Got 'therapist-v41.1.7'
[INFO ]    Retrieving 'soundSense_2015-1_194' from http://df.zweistein.cz/soundsense
[INFO ]    Got 'soundSense_2015-1_194'
[INFO ]    Retrieving 'legendsbrowser-1.19.0' from https://github.com/robertjanetzko/LegendsBrowser/releases/download/1.19
[INFO ]    Got 'legendsbrowser-1.19.0'
[INFO ]    Retrieving 'announcement-v1.3.0' from 'https://github.com/BrachystochroneSD/AnnouncementWindow'
[INFO ]    Got 'announcement-v1.3.0'
[INFO ]  Retrieving needed components' tarballs: done in 148.61s (at 02:30)
[INFO ]  =================================================================
[INFO ]  Extracting and patching components
[INFO ]    Extracting 'lnp-0.14a'
[INFO ]    Patching 'lnp-0.14a'
[INFO ]    Extracting 'df_47_04_linux'
[INFO ]    Extracting 'graphics-47.04'
[INFO ]    Extracting 'dfhack-0.47.04-r1'
[INFO ]    Patching 'dfhack-0.47.04-r1'
[INFO ]    Extracting 'twbt-04704'
[INFO ]    Extracting 'therapist-v41.1.7'
[INFO ]    Patching 'therapist-v41.1.7'
[INFO ]    Extracting 'soundSense_2015-1_194'
[INFO ]    Extracting 'announcement-v1.3.0'
[INFO ]    Patching 'announcement-v1.3.0'
[INFO ]  Extracting and patching components: done in 2.95s (at 02:33)
[INFO ]  =================================================================
[INFO ]  Building components
[INFO ]    =================================================================
[INFO ]    Building lnp-0.14a
[INFO ]    Building lnp-0.14a: done in 0.06s (at 02:33)
[INFO ]    =================================================================
[INFO ]    Credits for lnp-0.14a
[INFO ]    Credits for lnp-0.14a: done in 0.01s (at 02:33)
[INFO ]    =================================================================
[INFO ]    Building df-47_04_linux
[INFO ]      Already extracted 'df_47_04_linux'
[INFO ]    Building df-47_04_linux: done in 0.23s (at 02:33)
[INFO ]    =================================================================
[INFO ]    Credits for df-47_04_linux
[INFO ]    Credits for df-47_04_linux: done in 0.01s (at 02:33)
[INFO ]    =================================================================
[INFO ]    Building graphics-47.04
[INFO ]    Building graphics-47.04: done in 0.12s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Credits for graphics-47.04
[INFO ]    Credits for graphics-47.04: done in 0.00s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Building embark-2014-v3
[INFO ]    Building embark-2014-v3: done in 0.04s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Credits for embark-2014-v3
[INFO ]    Credits for embark-2014-v3: done in 0.01s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Building keybinds-master
[INFO ]    Building keybinds-master: done in 0.07s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Credits for keybinds-master
[INFO ]    Credits for keybinds-master: done in 0.00s (at 02:34)
[INFO ]    =================================================================
[INFO ]    Building dfhack-0.47.04-r1
[INFO ]    Building dfhack-0.47.04-r1: done in 153.28s (at 05:07)
[INFO ]    =================================================================
[INFO ]    Credits for dfhack-0.47.04-r1
[INFO ]    Credits for dfhack-0.47.04-r1: done in 0.01s (at 05:07)
[INFO ]    =================================================================
[INFO ]    Building twbt-04704
[INFO ]    Building twbt-04704: done in 0.02s (at 05:07)
[INFO ]    =================================================================
[INFO ]    Credits for twbt-04704
[INFO ]    Credits for twbt-04704: done in 0.01s (at 05:07)
[INFO ]    =================================================================
[INFO ]    Building therapist-v41.1.7
[INFO ]    Building therapist-v41.1.7: done in 35.83s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Credits for therapist-v41.1.7
[INFO ]    Credits for therapist-v41.1.7: done in 0.01s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Building soundsense-2015-1_194
[INFO ]    Building soundsense-2015-1_194: done in 0.10s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Credits for soundsense-2015-1_194
[INFO ]    Credits for soundsense-2015-1_194: done in 0.01s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Building legends-1.19.0
[INFO ]    Building legends-1.19.0: done in 0.03s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Credits for legends-1.19.0
[INFO ]    Credits for legends-1.19.0: done in 0.01s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Building announcement-v1.3.0
[INFO ]    Building announcement-v1.3.0: done in 0.07s (at 05:43)
[INFO ]    =================================================================
[INFO ]    Credits for announcement-v1.3.0
[INFO ]    Credits for announcement-v1.3.0: done in 0.01s (at 05:43)
[INFO ]  Building components: done in 190.26s (at 05:43)
[INFO ]  Build completed at 20200718.125424
[INFO ]  (elapsed: 5:42.90)
[INFO ]  Finishing installation (may take a few seconds)...

There were my dependencies from a new base-devel archlinux install:

sudo pacman -Syu base-devel cmake dos2unix git help2man jdk8-openjdk libxslt mercurial mesa ninja perl perl-xml-libxml perl-xml-libxslt python qt5-base qt5-tools sdl_image sdl_ttf tcl tk
sudo pacman -Syu libxml2
sudo pacman -Syu gperf
sudo pacman -Syu wget
sudo pacman -Syu rsync
sudo pacman -S extra/qt5-declarative

Don't know if it helps.

After that everything went well.

Have a good day.

P.

**Comment by McArcady** [comment]
Thanks for the feedback, I've updated the list of dependencies for Arch.
- is SoundSense still working well? I've not used it for ages.
- I recently added an 'AppImage' generation option (it generates a ~80MB standalone executable that should work on many distros). If you want to give it a try, I'm curious to see if it works well on ArchLinux.

**Comment by Hamblok0** [comment]
If you were still curious if the AppImage generation works on Arch, it doesn't seem to work.
![Screenshot_20200804_173513](https://user-images.githubusercontent.com/14968384/89352085-f26ef900-d678-11ea-8529-4531c43100e4.png)

**Comment by corollari** [comment]
I propose we disable the app image build step on all OSes except a few whitelisted ones.

Essentially I believe that building the app image doesn't fit any of the use cases that people would have for building the repo on their own, which IMO are:
- Just building it to use it yourself. If you are doing that then you would just use the normal build, as why would you want to use something that is inferior in every aspect except for portability when you've already generated build artifacts that target your specific system (thus not needing portability)?
- Verifying that the built code corresponds with the source code. This use case is already mostly covered by the CI (you could just download the build artifacts from there). Of course, it's possible to not trust the CI runners provided by github, but then people can just alter the scripts to re-enable building on their distribution.

Furthermore, in my experience app images are really buggy on all these obscure linux distributions (and even mainstream ones, I run fedora and I come across App Image bugs on a weekly basis), so it's highly unlikely that people building the package on these distros even want an app image.

**Comment by McArcady** [comment]
> If you were still curious if the AppImage generation works on Arch, it doesn't seem to work.
> ![Screenshot_20200804_173513](https://user-images.githubusercontent.com/14968384/89352085-f26ef900-d678-11ea-8529-4531c43100e4.png)

Ok thanks for the test!
The Appimage generation is meant to be used primarly on the Github CI so there's no need to investigate further (except if you have reasons to generate your own appimage).
Did you have the chance to test on your Arch system the Appimage built by Github [here](https://github.com/McArcady/lnp-forge/actions/runs/193249808) ?

**Comment by McArcady** [comment]
> I propose we disable the app image build step on all OSes except a few whitelisted ones.

I concur. The option is disabled by default in file `.config`.

> Essentially I believe that building the app image doesn't fit any of the use cases that people would have for building the repo on their own, which IMO are:
> 
> * Just building it to use it yourself. If you are doing that then you would just use the normal build, as why would you want to use something that is inferior in every aspect except for portability when you've already generated build artifacts that target your specific system (thus not needing portability)?
> * Verifying that the built code corresponds with the source code. This use case is already mostly covered by the CI (you could just download the build artifacts from there). Of course, it's possible to not trust the CI runners provided by github, but then people can just alter the scripts to re-enable building on their distribution.
> 
> Furthermore, in my experience app images are really buggy on all these obscure linux distributions (and even mainstream ones, I run fedora and I come across App Image bugs on a weekly basis), so it's highly unlikely that people building the package on these distros even want an app image.

lnp-forge builds the LinuxDwarfPack appimage using tool [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy), which is itself released as an Appimage, and subject to the issues you mentioned above.
As you said, we don't need this step to build on every distro (it already works well on Debian and the CI Ubuntu).

However I would be very interested to know how well the resulting LinuxDwarfPack Appimage runs on these distros:
- recent Ubuntu
- recent Fedora/Redhat
- recent Arch
(see #20)
In theory, it requires the same dependencies than the tar.gz version.

**Comment by corollari** [comment]
Just tested it on Fedora, build also fails.

> The option is disabled by default in file .config.

I see, looking around a bit it seems that it needs to be enabled through `echo "CT_APPIMAGE=y" >> .config`, but how come so many people have run into problems with it in their standard build processes? Am I missing something?

**Comment by Hamblok0** [comment]
> > If you were still curious if the AppImage generation works on Arch, it doesn't seem to work.
> > ![Screenshot_20200804_173513](https://user-images.githubusercontent.com/14968384/89352085-f26ef900-d678-11ea-8529-4531c43100e4.png)
> 
> Ok thanks for the test!
> The Appimage generation is meant to be used primarly on the Github CI so there's no need to investigate further (except if you have reasons to generate your own appimage).
> Did you have the chance to test on your Arch system the Appimage built by Github [here](https://github.com/McArcady/lnp-forge/actions/runs/193249808) ?

This is the output I get when trying to run the appimage. This was also after running ```chmod a+x``` on the appimage as well. 

```Starting LinuxDwarfPack-0.47.04-r3-x86_64
- configuration and game saves are stored in /home/greylodge/.lnp/
- feedback or issues? see http://www.bay12forums.com/smf/index.php?topic=157712
- created with lnp-forge: https://github.com/McArcady/lnp-forge

Creating overlay of /home/greylodge/.lnp/ and /tmp/.mount_LinuxDknP6sa in /tmp/lnp-4CJ5lq...
/tmp/.mount_LinuxDknP6sa/AppRun: line 21: UID: readonly variable```

**Comment by McArcady** [comment]
Interestingly, this does not happen in the AppImage context when run on
Fedora.
I pushed an update of the appimage start-up script that renames the
litigious vars UID, GID.
The new AppImage should be updated in 1H here:
https://github.com/McArcady/lnp-forge/actions/runs/196753676


Le mer. 5 août 2020 à 20:58, Joseph Cooper <notifications@github.com> a
écrit :

**Comment by Hamblok0** [comment]
Still getting the exact same error when I run the new appimage.
